### ISSUE TITLE
Error installing requirements and running the setup_and_install.sh

### ISSUE THREAD

**Issue by aXlireza** [sguldemond/moon-paper#4]
Hi there
My first error was here:
```
(base) axlireza@axlireza:~/moon-paper$ pip install -r requirements.txt
Collecting astroid==2.3.3 (from -r requirements.txt (line 1))
  Using cached astroid-2.3.3-py3-none-any.whl (205 kB)
Collecting beautifulsoup4==4.8.1 (from -r requirements.txt (line 2))
  Using cached beautifulsoup4-4.8.1-py3-none-any.whl (101 kB)
Collecting isort==4.3.21 (from -r requirements.txt (line 3))
  Using cached isort-4.3.21-py2.py3-none-any.whl (42 kB)
Collecting lazy-object-proxy==1.4.3 (from -r requirements.txt (line 4))
  Using cached lazy-object-proxy-1.4.3.tar.gz (34 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting mccabe==0.6.1 (from -r requirements.txt (line 5))
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0
```

the second one:
```
(base) axlireza@axlireza:~/moon-paper$ ./setup_and_install.sh
Traceback (most recent call last):
  File "/home/axlireza/moon-paper/phase-scrapper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
Traceback (most recent call last):
  File "/home/axlireza/moon-paper/daily_schedule.py", line 9, in <module>
    phase_schedule = json.loads(phase_json)
  File "/home/axlireza/anaconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/axlireza/anaconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/axlireza/anaconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
cp: 'change_background.py' and '/home/axlireza/moon-paper/change_background.py' are the same file
Traceback (most recent call last):
  File "/home/axlireza/moon-paper/crontab_setter.py", line 1, in <module>
    from crontab import CronTab
ModuleNotFoundError: No module named 'crontab'
Traceback (most recent call last):
  File "/home/axlireza/moon-paper/change_background.py", line 55, in <module>
    set_angle()
  File "/home/axlireza/moon-paper/change_background.py", line 15, in set_angle
    img_schedule = json.loads(schedule_json)
  File "/home/axlireza/anaconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/axlireza/anaconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/axlireza/anaconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Any idea why this is happening?

**Comment by sguldemond** [comment]
Hi, super random to respond to this after 3 years. You need to install the requirements.txt in a virtual environment first. Thank you for trying to use my little hobby project here 3 years ago 💪
